###LISTAR TODOS LOS CONTACTOS
GET http://localhost:8080/api/contacto/lista

###BUSCAR CONTACTO POR ID
GET http://localhost:8080/api/contacto/1

###GUARDAR CONTACTO
POST http://localhost:8080/api/contacto/save
Content-Type: application/json

{
  "nombre": "Estrella",
  "apellidoUno": "Tinoco",
  "apellidoDos": "Lara",
  "telefono": 689868598
}

###MODIFICAR CONTACTO
PUT http://localhost:8080/api/contacto/1
Content-Type: application/json

{
  "nombre": "Brais",
  "apellidoUno": "Suárez",
  "apellidoDos": "Miguéns",
  "telefono": 689868598
}

###ELIMINAR CONTACTO
DELETE http://localhost:8080/api/contacto/2